### ISSUE TITLE
"Load in Stremio App" doesn't go thru

### ISSUE THREAD

**Issue by beasteers** [sungshon/PimpMyStremio#71]
I'm running on Mac OSX Mojave with PMS `1.2.2` and Stremio `4.4` and when I click "Load in Stremio App" (LOSA) from the mac task bar, it doesn't do anything. 

----
I tried clicking it while running with `--verbose` and I get:
```
$ ./PimpMyStremio --verbose
PimpMyStremio - Checking for updates
PimpMyStremio - Already have latest version
PimpMyStremio - User defined add-ons list URL is valid, updating add-ons list
PimpMyStremio - Successfully updated add-ons list from remote source
Remote access choice: No (local)
PimpMyStremio server running at: http://127.0.0.1:7777
systrayhelper 0.0.5 (d5794e2a72a9cb160d78b6fd9ee640ad1df02af7 built 2018-12-04T21:05:51Z)
Non-critical: Could not auto-open webpage, presuming Linux OS
Error: Exited with code 1
    at ChildProcess.module.exports.subprocess.once.exitCode (/snapshot/src/node_modules/open/index.js:122:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
```

----
When I click on "LOSA" from the web app (the external button at the top), it opens a new tab and goes to: `stremio://127.0.0.1:7777/catalog.json` and nothing happens - it doesn't connect to the app and it doesn't show the `catalog.json` content. 

The same thing happens when I install and enable "Awesome Everything" and click the addon settings button and click Load->"LOSA"

This pops up in the js console after pressing the button:
```
Uncaught ReferenceError: loadApp is not defined
    at HTMLButtonElement.onclick ((index):1)
```

And these errors are there on boot:
```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.   
   127.0.0.1/:1

GET http://127.0.0.1:7777/[object%20HTMLLinkElement] 404 (Not Found). 
   [object%20HTMLLinkElement]:1
```

**Comment by sungshon** [comment]
> When I click on "LOSA" from the web app (the external button at the top), it opens a new tab and goes to: stremio://127.0.0.1:7777/catalog.json and nothing happens - it doesn't connect to the app and it doesn't show the catalog.json content.

Yes, there is currently a Stremio bug on OSX that breaks support for `stremio://` links, I've reported this and they ensured me that it will be fix in the next release.

For now, the workaround for OSX users is to press the gear icon next to an addon, then press "Add-on URL (click to copy)". After that go to Stremio and paste the addon url in the search field and press enter, this should load the addon.

The other errors you pasted seem strange, I will look into them as soon as i find the time.

**Comment by sungshon** [comment]
uhm, i'm not getting this error:
```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.   
   127.0.0.1/:1

GET http://127.0.0.1:7777/[object%20HTMLLinkElement] 404 (Not Found). 
   [object%20HTMLLinkElement]:1
```

Can't think what could be causing it for now.

```
Uncaught ReferenceError: loadApp is not defined
    at HTMLButtonElement.onclick ((index):1)
```

Yes, this one is a bug, I will fix it, although it should not cause any issues at all, it's just some old code I forgot to remove.

**Comment by sungshon** [comment]
Can you give me some more info on this error:
```
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.   
   127.0.0.1/:1

GET http://127.0.0.1:7777/[object%20HTMLLinkElement] 404 (Not Found). 
   [object%20HTMLLinkElement]:1
```
?

You get it when starting PimpMyStremio?
