### ISSUE TITLE
How can I change External to LAN Ip using command line ?

### ISSUE THREAD

**Issue by chicungunya** [sungshon/PimpMyStremio#89]
Hello,
Since I put External in my settings, PMS doesn't work anymore.
I tried to uninstall and reinstall but same error.

So how can I come back to LAN settings and not external? 

darnaga@raspberrypi:/home/darnaga/PimpMyStremio/src $ npm start

> pimpmystremio@1.2.2 start /home/darnaga/PimpMyStremio/src
> node index.js

Remote access choice: External
Retrieving external IP ...

/home/darnaga/PimpMyStremio/src/node_modules/superagent/lib/node/index.js:729
  if (2 == fn.length) return fn(err, res);
                             ^
TypeError: Cannot read property '0' of null
    at /home/darnaga/PimpMyStremio/src/node_modules/externalip/index.js:11:52
    at Request.callback (/home/darnaga/PimpMyStremio/src/node_modules/superagent/lib/node/index.js:729:30)
    at Request.<anonymous> (/home/darnaga/PimpMyStremio/src/node_modules/superagent/lib/node/index.js:135:10)
    at Request.emit (events.js:198:13)
    at Stream.<anonymous> (/home/darnaga/PimpMyStremio/src/node_modules/superagent/lib/node/index.js:906:12)
    at Stream.emit (events.js:203:15)
    at Unzip.<anonymous> (/home/darnaga/PimpMyStremio/src/node_modules/superagent/lib/node/utils.js:124:12)
    at Unzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pimpmystremio@1.2.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pimpmystremio@1.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Thanks

**Comment by zany130** [comment]
did you ever figure this out @chicungunya ? Im having this issue to
